# LOCAL DEVELOPMENT CONFIGURATION:
# This docker-compose.local.yml is designed for local development:
# - Uses standard Docker Compose syntax (no Swarm-specific features)
# - Builds the web service from local source code instead of using a pre-built image
# - Maps to localhost instead of a production domain
# - Uses different ports (8000, 8081) to avoid conflicts with local services
# - Loads Traefik config from ./config/traefik.local.yml
# - To run: use 'docker compose -f docker-compose.local.yml up --build -d'
# - For multi-app setup: create a shared network with 'docker network create traefik-local'

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`app1.localhost`)"
      - "traefik.http.services.web-service.loadbalancer.server.port=3000"

  reverse-proxy:
    image: traefik:v3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.local.yml:/etc/traefik/traefik.yml
    ports:
      - "8000:80"
      - "8081:8080"
    networks:
      - traefik-local

networks:
  traefik-local:
    external: true
