version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web-service.loadbalancer.server.port=3000"

  reverse-proxy:
    image: traefik:v3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.local.yml:/etc/traefik/traefik.yml
    ports:
      - "8000:80"
      - "8081:8080"
