all:
  hosts:
    localhost:
      ansible_connection: local
    vps:
      ansible_host: "{{ lookup('env', 'SSH_HOST') }}"
      ansible_user: "{{ lookup('env', 'SSH_USER') }}"
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
