---
# Tasks for installing actual dependencies

- name: Set default uv_executable if not defined
  ansible.builtin.set_fact:
    uv_executable: "{{ uv_executable | default('uv') }}"
  tags: python_deps

- name: Set remote_role_path fact
  ansible.builtin.set_fact:
    remote_role_path: "~/vps-swarm-local-vps-development/infraestructura/ansible/collections/ansible_collections/kiri/vps/roles/dependency"
  tags: python_deps

- name: create virtual enviroment if does not exist 
  ansible.builtin.shell: uv venv vps-deps
  tags: python_deps

# the shell collections by default run on the remote host
- name: Install Python dependencies using uv sync with venv
  ansible.builtin.shell: |
    cd {{ remote_role_path }}/files && {{ uv_executable }} sync
  tags: python_deps

- name: Display installed packages
  ansible.builtin.shell: |
    cd {{ remote_role_path }}/files && {{ uv_executable }} pip list
  register: installed_packages
  changed_when: false
  tags: python_deps

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ installed_packages.stdout_lines }}"
  tags: python_deps
