---
# Tasks for installing actual dependencies

- name: Set default uv_executable if not defined
  ansible.builtin.set_fact:
    uv_executable: "{{ uv_executable | default('uv') }}"
  tags: python_deps

- name: Install Python dependencies using uv sync with venv
  ansible.builtin.shell: |
    cd {{ collections_dir }}/kiri/vps/roles/dependency/files && {{ uv_executable }} sync --venv {{ ansible_env.HOME }}/.venv/vps-deps
  delegate_to: "{{ inventory_hostname }}"
  tags: python_deps

- name: Display installed packages
  ansible.builtin.shell: |
    {{ uv_executable }} pip list --venv {{ ansible_env.HOME }}/.venv/vps-deps
  register: installed_packages
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  tags: python_deps

- name: Show installed packages
  ansible.builtin.debug:
    msg: "{{ installed_packages.stdout_lines }}"
  tags: python_deps
