---
# Tasks for installing actual dependencies

- name: Check if required Python packages are installed
  ansible.builtin.shell: |
    $HOME/.cargo/bin/uv pip list
  register: pip_list
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  tags: python_deps

- name: Install Python dependencies
  ansible.builtin.shell: |
    $HOME/.cargo/bin/uv pip install jsondiff docker pyyaml
  when: "'jsondiff' not in pip_list.stdout or 'docker' not in pip_list.stdout or 'pyyaml' not in pip_list.stdout"
  delegate_to: "{{ inventory_hostname }}"
  tags: python_deps
