---
# Tasks for installing package managers

- name: Check if Python uv is installed
  ansible.builtin.command: which uv
  register: uv_check
  changed_when: uv_check.rc != 0
  ignore_errors: true
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Install Python uv if not installed
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: uv_check.rc != 0
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Get uv installation path
  ansible.builtin.shell: |
    echo "$HOME/.cargo/bin/uv"
  register: uv_path
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Display Python uv status
  ansible.builtin.debug:
    msg: "Python uv is {{ 'installed' if uv_check.rc == 0 else 'not installed' }} at {{ uv_path.stdout | trim }}"
  tags: uv