---
# Tasks for installing package managers

- name: Check if Python uv is installed
  ansible.builtin.command: which uv
  register: uv_check
  changed_when: uv_check.rc != 0
  ignore_errors: true
  tags: uv

- name: Install Python uv if not installed
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: uv_check.rc != 0
  tags: uv

- name: Display Python uv status
  ansible.builtin.debug:
    msg: "Python uv is {{ 'installed' if uv_check.rc == 0 else 'not installed' }}"
  tags: uv