---
# Tasks for installing package managers

- name: Check if uv binary exists in .cargo/bin
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/uv"
  register: uv_binary
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Install Python uv if not installed
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: not uv_binary.stat.exists
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Verify uv installation
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/uv"
  register: uv_installed
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Display Python uv status
  ansible.builtin.debug:
    msg: "Python uv is {{ 'installed' if uv_installed.stat.exists else 'not installed' }} at {{ ansible_env.HOME }}/.cargo/bin/uv"
  tags: uv
