---
# Tasks for installing package managers

- name: Check if uv binary exists
  ansible.builtin.shell: |
    which uv || echo ""
  register: uv_which
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Install Python uv if not installed
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    executable: /bin/bash
  when: uv_which.stdout == ""
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

# Just a lot of finding to see where the github action decide where to store the uv
# i know the github action is not responsible for where to put the downloaded uv but the installation have different effect running on local than on the vps
- name: Find uv binary after installation
  ansible.builtin.shell: |
    find {{ ansible_env.HOME }} -name uv -type f 2>/dev/null || echo ""
  register: find_uv
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  tags: uv

- name: Display uv binary location
  ansible.builtin.debug:
    msg: "Found uv at: {{ find_uv.stdout_lines[0] | default('') }}"
  when: find_uv.stdout_lines | length > 0
  tags: uv

- name: Set uv path fact
  ansible.builtin.set_fact:
    uv_path: "{{ find_uv.stdout_lines[0] | default('') }}"
  tags: uv

- name: Display Python uv status and location
  ansible.builtin.debug:
    msg: >
      {% if uv_path %}
      Python uv is installed at {{ uv_path }}
      {% else %}
      Python uv was not found in the home directory
      {% endif %}
  tags: uv

- name: Check alternative locations for uv
  ansible.builtin.shell: |
    which uv || echo ""
  register: which_uv
  changed_when: false
  delegate_to: "{{ inventory_hostname }}"
  when: not uv_path
  tags: uv

- name: Display alternative uv location
  ansible.builtin.debug:
    msg: "Found uv at: {{ which_uv.stdout }}"
  when: not uv_path and which_uv.stdout != ""
  tags: uv

- name: Set final uv path
  ansible.builtin.set_fact:
    uv_executable: "{{ uv_path | default(which_uv.stdout if not uv_path else '') | default('uv') }}"
  tags: uv
