# App2 LOCAL DEVELOPMENT CONFIGURATION:
# This docker-compose.local.yml is designed for local development with Traefik
# - Uses standard Docker Compose syntax (no Swarm-specific features)
# - Builds the app2 service from local source code
# - To run: use 'docker compose -f docker-compose.local.yml up --build -d'
# - Requires the traefik-local network to be created first

version: "3"

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app2.localhost`)"
      - "traefik.http.services.app2-service.loadbalancer.server.port=3000"

networks:
  traefik-local:
    external: true
