- name: Minimal Hello World
  hosts: all
  gather_facts: no  # Desactivamos la recopilación de hechos
  
  tasks:
    - name: Create hello world file
      copy:
        content: "Hello from GitHub Actions!"
        dest: "/home/kiri/hello-from-github-actions.txt"
        mode: '0644'
