api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: traefik-local

entryPoints:
  web:
    address: ":80"

log:
  level: DEBUG

accessLog: {}

# Enable local domain resolution
# For local development, add entries to your /etc/hosts file:
# 127.0.0.1 app1.localhost app2.localhost
