api:
  insecure: true
  dashboard: true

providers:
  swarm:
    # how to comunicate with docker in swarm mode to find labels and service
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: kiri231@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: true

log:
  level: DEBUG

accessLog: {}