name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create ansible.cfg
      run: |
        echo "[defaults]" > ansible.cfg
        echo "host_key_checking = False" >> ansible.cfg
        echo "inventory = ${{ github.workspace }}/infraestructura/ansible/kiri/vps/inventory.yml" >> ansible.cfg
        echo "[ssh_connection]" >> ansible.cfg
        echo "pipelining = True" >> ansible.cfg

    - name: Create vault password file
      run: |
        echo "${{ secrets.VAULT_PASSWORD }}" > .vault_password
        
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
  
    - name: Set environment variables
      run: |
        echo "SSH_HOST=${{ secrets.SSH_HOST }}" >> $GITHUB_ENV
        echo "SSH_USER=${{ secrets.SSH_USER }}" >> $GITHUB_ENV
        echo "ANSIBLE_DIR=${{ github.workspace }}/infraestructura/ansible/kiri/vps" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        uvx --from ansible-core --with ansible ansible-playbook ${{ env.ANSIBLE_DIR }}/playbooks/deploy.yml --vault-password-file .vault_password
