name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set environment variables based on branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
        else
          echo "ENV=staging" >> $GITHUB_ENV
        fi
        
    - name: Install Ansible
      run: |
        pip install ansible
        
    - name: Set up SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Run Ansible playbook
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        export ANSIBLE_SSH_PASS=$SSH_PASSPHRASE
        sshpass -p "$SSH_PASSPHRASE" ansible-playbook -i "$SSH_HOST," \
        -u "$SSH_USER" \
        --private-key=~/.ssh/id_ed25519 \
        --ssh-common-args="-o StrictHostKeyChecking=no" \
        ${{ github.workspace }}/insfraestructura/ansible/ansibleTestGithub.yml

